name: Testing Secret Variables

on:
  workflow_dispatch:

env:
      ACTIONS_STEP_DEBUG: true

jobs:
  tset_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Secret Variable"
        run: |
          echo "Secret Value : ${{ secrets.TEST_KEY }}"
